<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:py="http://genshi.edgewall.org/"
      lang="en">
    <head>
        <title>html5lib Based HTML Parser</title>
        <link rel="stylesheet" href="/html5/styles.css"/>
    </head>
    <body>
        <h1>html5lib Based HTML Parser</h1>
        <section class="error">
            <h2>Error</h2>
            <div py:choose="document.error" py:strip="True">
                <p py:when="document.errors['CANT_LOAD']">
                    The URI <a href="${document.uri}"><code>${document.uri}</code></a> could not be loaded. Ensure that the URI is correctly entered and the server is responding.
                </p>
                <p py:when="document.errors['INVALID_URI']">
                    <code>"${document.uri}"</code> is not a recognised URI (only <code>http</code> and <code>https</code> URI schemes are supported).
                    <py:if test="not document.uri">You may have left the URI box blank by mistake.</py:if>
                </p>
                <p py:otherwise="">An unexpected internal error occured. This is probably a bug in the script. If you can reproduce the problem, please <a href="http://code.google.com/p/html5/issues/entry">file it as a bug</a> stating the input that caused the problem.
                </p>
            </div>
        </section>
    </body>
</html>